on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.branch }}"
